[tox]
envlist =
    py{310,311}-dj{42,52},
    py312-dj{42,52,60},
    py{313,314}-dj{52,60}

[testenv]
usedevelop = true
commands =
    rm -rf responsediff/tests/response_fixtures/MixinTest.test_assertWebsiteSame/
    rm -rf responsediff/tests/response_fixtures/MixinTest.test_recursion/
    rm -rf responsediff/tests/response_fixtures/TestResponseDiff.test_story.content
    rm -rf responsediff/tests/response_fixtures/TestResponseDiff.test_story.metadata
    pytest -vv --cov=responsediff --strict-markers -r fEsxXw {posargs:responsediff}
allowlist_externals =
    rm
deps =
    pytest
    pytest-django
    pytest-cov
    coverage
    dj42: Django>=4.2,<5.0
    dj52: Django>=5.2,<6.0
    dj60: Django>=6.0,<7.0
setenv =
    DJANGO_SETTINGS_MODULE=responsediff.tests.project.settings
passenv = TEST_*, DBDIFF_*, FIXTURE_*

[testenv:qa]
basepython = python3.12
commands =
    ruff check responsediff
deps =
    ruff
